/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dateoutput;

import java.util.Date;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws InterruptedException {
//        System.out.println(new App().getGreeting());
        while (true) {
            Date date = new Date();
            System.out.println(date.toString());
            Thread.sleep(1000);
        }
    }
}
